# Variables
name: TALA
author: IT3
description: Cybersecurity Consultancy Firm

# Github
domain: tala.soon.it
url: https://tala.soon.it
baseurl: /

# Exclude Files
exclude:
  - "*.nix"
  - "*.bash"
  - "*.md"
  - Gemfile*
  - CNAME
  - vendor