title: Test
email: test@example.com
description: >-
  Sample description
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Github
domain: tala.soon.it
url: https://tala.soon.it
baseurl: /tala/
