# Variables
name: TALA
author: IT3
description: Cybersecurity Consultancy Firm

# References
youtube: "https://www.youtube.com/@TalaSecurity"

# Info
email: "talasecurespace@gmail.com"

# Github
domain: tala.soon.it
url: https://tala.soon.it
baseurl: /

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude Files
exclude:
  - "*.nix"
  - "*.bash"
  - "*.md"
  - Gemfile*
  - CNAME
  - vendor